title: "Keyhan Kouhkiloui"

logo: /assets/img/Keyhan_Kouhkiloui.png
float_logo: true

description: Robotics Research Scientist

email: kkouhkil@ed.ac.uk

# show_downloads: true
# theme: jekyll-theme-minimal

