gems:
  - jemoji
  - jekyll-paginate

title: "Keyhan Kouhkiloui"

description: >
  Robotics Research Scientist

logo: /assets/img/Keyhan_Kouhkiloui.png
float_logo: true

email: kkouhkil@ed.ac.uk

# show_downloads: true
# theme: jekyll-theme-minimal

